config/routes.rb
Rails.application.routes.draw do
  resources :players, only: [:show, :index]
  resources :notifing_stats
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notifing_stat.rb
class NotifingStat < ApplicationRecord
  belongs_to :user
  belongs_to :player
end

app/controllers/notifing_stats_controller.rb
class NotifingStatsController < ApplicationController
  before_action :set_notifing_stat, only: %i[ show edit update destroy ]

  # GET /notifing_stats or /notifing_stats.json
  def index
    @notifing_stats = NotifingStat.all
  end

  # GET /notifing_stats/1 or /notifing_stats/1.json
  def show
  end

  # GET /notifing_stats/new
  def new
    @notifing_stat = NotifingStat.new
    @player = get_player
    @kind = get_kind
    @previous_stat = get_previous_stat
  end

  # GET /notifing_stats/1/edit
  def edit
  end

  # POST /notifing_stats or /notifing_stats.json
  def create
    @notifing_stat = NotifingStat.new(notifing_stat_params)

    respond_to do |format|
      if @notifing_stat.save
        format.html { redirect_to @notifing_stat, notice: "Notifing stat was successfully created." }
        format.json { render :show, status: :created, location: @notifing_stat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notifing_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifing_stats/1 or /notifing_stats/1.json
  def update
    respond_to do |format|
      if @notifing_stat.update(notifing_stat_params)
        format.html { redirect_to @notifing_stat, notice: "Notifing stat was successfully updated." }
        format.json { render :show, status: :ok, location: @notifing_stat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notifing_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifing_stats/1 or /notifing_stats/1.json
  def destroy
    @notifing_stat.destroy
    respond_to do |format|
      format.html { redirect_to notifing_stats_url, notice: "Notifing stat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notifing_stat
      @notifing_stat = NotifingStat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notifing_stat_params
      params.require(:notifing_stat).permit(:user_id, :player_id, :kind, :target, :previous_stat)
    end

    def get_player
      @player = Player.find(params[:player_id])
    end

    def get_kind
      @kind = params[:kind]
    end

    def get_previous_stat
      @previous_stat = params[:previous_stat]
    end
end

app/helpers/notifing_stats_helper.rb
module NotifingStatsHelper
end

app/views/notifing_stats/_form.html.erb
<%= @player.name %>選手の
<% if @player.pitcher? %>
  現在<%= @player.pitcher_stat.games %>
<% end %>

<% if @player.fielder? %>
  現在<%= @player.fielder_stat.games %>の試合数を
<% end %>

<%= form_with(model: notifing_stat) do |form| %>
  <% if notifing_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notifing_stat.errors.count, "error") %> prohibited this notifing_stat from being saved:</h2>

      <ul>
        <% notifing_stat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, :value =>  current_user.id %>
  </div>

  <div class="field">
    <%= form.hidden_field :player_id, :value =>  @player.id %>
  </div>

  <div class="field">
    <%= form.hidden_field :kind, :value =>  @kind %>
  </div>

  <div class="field">
    <%= form.label :"目標" %><%= form.number_field :target %>
    を達成するまで通知を送ります！
  </div>

  <div class="field">
    <%= form.hidden_field :previous_stat, :value =>  @previous_stat %>
  </div>

  <div class="actions">
    <%= form.submit value= "登録" %>
  </div>
<% end %>

app/views/notifing_stats/edit.html.erb
<h1>Editing Notifing Stat</h1>

<%= render 'form', notifing_stat: @notifing_stat %>

<%= link_to 'Show', @notifing_stat %> |
<%= link_to 'Back', notifing_stats_path %>

app/views/notifing_stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifing Stats</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Player</th>
      <th>Kind</th>
      <th>Target</th>
      <th>Previous stat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifing_stats.each do |notifing_stat| %>
      <tr>
        <td><%= notifing_stat.user_id %></td>
        <td><%= notifing_stat.player_id %></td>
        <td><%= notifing_stat.kind %></td>
        <td><%= notifing_stat.target %></td>
        <td><%= notifing_stat.previous_stat %></td>
        <td><%= link_to 'Show', notifing_stat %></td>
        <td><%= link_to 'Edit', edit_notifing_stat_path(notifing_stat) %></td>
        <td><%= link_to 'Destroy', notifing_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notifing Stat', new_notifing_stat_path %>

app/views/notifing_stats/new.html.erb
<h1>通知される記録の登録</h1>

<%= render 'form', notifing_stat: @notifing_stat %>

<%= link_to 'Back', notifing_stats_path %>

app/views/notifing_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @notifing_stat.player_id %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @notifing_stat.kind %>
</p>

<p>
  <strong>Target:</strong>
  <%= @notifing_stat.target %>
</p>

<p>
  <strong>Previous stat:</strong>
  <%= @notifing_stat.previous_stat %>
</p>

<%= link_to '編集', edit_notifing_stat_path(@notifing_stat) %> |
<%= link_to '削除', notifing_stat_path(@notifing_stat), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to '登録一覧', notifing_stats_path %>