config/routes.rb
Rails.application.routes.draw do
  resources :players, only: [:show, :index]
  resources :notifing_stats
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  has_one :pitcher_stat
  has_one :fielder_stat

  def pitcher?
    position == "投手"
  end

  def fielder?
    position != "投手"
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_fielder_stats.html.slim
- if fielder_stat.games.nil?
  | #{@player.name}選手にはまだ一軍成績がありません
- else
  li  = link_to new_notifing_stat_path(player_id: @player.id, kind: "games", previous_stat: fielder_stat.games) do
    | 試合数:#{fielder_stat.games}
  li  = link_to new_notifing_stat_path(player_id: @player.id, kind: "plate_appearances", previous_stat: fielder_stat.plate_appearances) do
    | 打席数:#{fielder_stat.plate_appearances}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "at_bats", previous_stat: fielder_stat.at_bats) do
    | 打数:#{fielder_stat.at_bats}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "runs", previous_stat: fielder_stat.runs) do
    | 得点:#{fielder_stat.runs}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "hits", previous_stat: fielder_stat.hits) do
    | 安打:#{fielder_stat.hits}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "two_base_hits", previous_stat: fielder_stat.two_base_hits) do
    | 二塁打:#{fielder_stat.two_base_hits}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "three_base_hits", previous_stat: fielder_stat.three_base_hits) do
    | 三塁打:#{fielder_stat.three_base_hits}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "home_runs", previous_stat: fielder_stat.home_runs) do
    | 本塁打:#{fielder_stat.home_runs}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "base_hit", previous_stat: fielder_stat.base_hit) do
    | 塁打:#{fielder_stat.base_hit}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "RBI", previous_stat: fielder_stat.RBI) do
    | 打点:#{fielder_stat.RBI}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "stolen_base", previous_stat: fielder_stat.stolen_base) do
    | 盗塁:#{fielder_stat.stolen_base}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "caught_stealing", previous_stat: fielder_stat.caught_stealing) do
    | 盗塁刺:#{fielder_stat.caught_stealing}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "sacrifice_bunts", previous_stat: fielder_stat.sacrifice_bunts) do
    | 犠打:#{fielder_stat.sacrifice_bunts}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "sacrifice_flys", previous_stat: fielder_stat.sacrifice_flys) do
    | 犠飛:#{fielder_stat.sacrifice_flys}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "base_on_balls", previous_stat: fielder_stat.base_on_balls) do
    | 四球:#{fielder_stat.base_on_balls}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "hits_by_pitch", previous_stat: fielder_stat.hits_by_pitch) do
    | 死球:#{fielder_stat.hits_by_pitch}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "strike_outs", previous_stat: fielder_stat.strike_outs) do
    | 三振:#{fielder_stat.strike_outs}
  li = link_to link_to new_notifing_stat_path(player_id: @player.id, kind: "double_play", previous_stat: fielder_stat.double_play) do
    | 併殺打:#{fielder_stat.double_play}
  li 打率: #{fielder_stat.batting_average}
  | (打率は通知できません。)
  li 出塁率: #{fielder_stat.on_base_percentage}
  | (出塁率は通知できません。)
  li 長打率: #{fielder_stat.slugging_percentage}
  | (長打率は通知できません。)
  li OPS: #{fielder_stat.on_base_plus_slugging}
  | (OPSは通知できません。)

app/views/players/_pitcher_stats.html.slim
- if pitcher_stat.games.nil?
  | #{@player.name}選手にはまだ一軍成績がありません
- else
  li  = link_to new_notifing_stat_path(player_id: @player.id, kind: "games", previous_stat: pitcher_stat.games) do
    | 試合数:#{pitcher_stat.games}
  li  = link_to new_notifing_stat_path(player_id: @player.id, kind: "win_pitchers", previous_stat: pitcher_stat.win_pitchers) do
    | 勝利:#{pitcher_stat.win_pitchers}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "lost_pitchers", previous_stat: pitcher_stat.lost_pitchers) do
    | 敗北:#{pitcher_stat.lost_pitchers}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "saves", previous_stat: pitcher_stat.saves) do
    | セーブ:#{pitcher_stat.saves}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "holds", previous_stat: pitcher_stat.holds) do
    | ホールド:#{pitcher_stat.holds}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "hold_points", previous_stat: pitcher_stat.hold_points) do
    | HP:#{pitcher_stat.hold_points}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "complete_games", previous_stat: pitcher_stat.complete_games) do
    | 完投:#{pitcher_stat.complete_games}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "shut_outs", previous_stat: pitcher_stat.shut_outs) do
    | 完封勝利:#{pitcher_stat.shut_outs}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "no_base_on_balls", previous_stat: pitcher_stat.no_base_on_balls) do
    | 無四球:#{pitcher_stat.no_base_on_balls}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "hitters", previous_stat: pitcher_stat.hitters) do
    | 打者:#{pitcher_stat.hitters}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "innings_pitched", previous_stat: pitcher_stat.innings_pitched) do
    | 投球回:#{pitcher_stat.innings_pitched}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "hits_Allowed", previous_stat: pitcher_stat.hits_Allowed) do
    | 被安打:#{pitcher_stat.hits_Allowed}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "home_runs_allowed", previous_stat: pitcher_stat.home_runs_allowed) do
    | 被本塁打:#{pitcher_stat.home_runs_allowed}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "base_on_balls", previous_stat: pitcher_stat.base_on_balls) do
    | 与四球:#{pitcher_stat.base_on_balls}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "hits_by_pitch", previous_stat: pitcher_stat.hits_by_pitch) do
    | 与死球:#{pitcher_stat.hits_by_pitch}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "strike_outs", previous_stat: pitcher_stat.strike_outs) do
    | 奪三振:#{pitcher_stat.strike_outs}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "wild_pitchs", previous_stat: pitcher_stat.wild_pitchs) do
    | 暴投:#{pitcher_stat.wild_pitchs}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "balks", previous_stat: pitcher_stat.balks) do
    | ボーク:#{pitcher_stat.balks}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "runs_allowed", previous_stat: pitcher_stat.runs_allowed) do
    | 失点:#{pitcher_stat.runs_allowed}
  li = link_to new_notifing_stat_path(player_id: @player.id, kind: "earned_runs", previous_stat: pitcher_stat.earned_runs) do
    | 自責点:#{pitcher_stat.earned_runs}
  li 防御率: #{pitcher_stat.earned_runs_average}
  | (防御率は通知できません。)
  li whip: #{pitcher_stat.whip}
  | (whipは通知できません。)

    

app/views/players/_player.html.slim
 li
   = player.uniform_number
   = link_to player.name, player_path(id: player.id)
   = player.position

app/views/players/index.html.slim
選手一覧
= render @players

app/views/players/show.html.slim
.page-body
  .h1
    = @player.name + "選手の成績一覧"
    - if @player.pitcher? 
      = render "pitcher_stats", pitcher_stat: @player.pitcher_stat
    - if @player.fielder?
      = render "fielder_stats", fielder_stat: @player.fielder_stat